FROM tomcat:9.0-jdk17

# Remove default ROOT app
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copy your Maven-generated WAR file
COPY target/*.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080

CMD ["catalina.sh", "run"]








app.py

from flask import Flask
app = Flask(__name__)
@app.route("/")
def home():
    return "Hello from me"
if __name__ == "__main__":
 app. run (host="0.0.0.0", port=5000)